[package]
name = "ruka"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# $env:FFMPEG_PKG_CONFIG_PATH="C:\src\vcpkg\installed\x64-windows-static-md\lib\pkgconfig\"


[dependencies]
clap = { version = "4.3", features = ["derive"] }
rustube = "0.6"
tokio = { version = "1", features = ["full"] }
mini-redis = "0.4.1"
serde = "1.0"
serde_json = "1.0"
reqwest = { version = "0.11.18", features = ["stream"] }
anyhow = "1.0.75"
futures-util = "0.3.28"
ffmpeg-next = { version = "6.0.0", features = ["ffmpeg43"] }
