[package]
name = "ruka"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# $env:FFMPEG_PKG_CONFIG_PATH="C:\src\vcpkg\installed\x64-windows-static-md\lib\pkgconfig\"


[dependencies]
thiserror = "1"
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }

futures-util = "0.3"
rustube = "0.6"
mini-redis = "0.4"
serde = "1.0"
serde_json = "1.0"
reqwest = { version = "0.11", features = ["stream"] }
ffmpeg-next = { version = "6" }

[dev-dependencies]
anyhow = "1"